[package]
name = "hardcover_wrapper"
description = "A Rust API wrapper for the Hardcover API, providing fully typed data."
version = "0.1.0"
edition = "2021"
license = "LGPL-2.1"
readme = "README.md"
repository = "https://github.com/socalledtheraven/hardcover-wrapper"
keywords = ["hardcover", "books", "graphql", "api"]
categories = ["api-bindings"]

[dependencies]
reqwest = { version = "0.13.4", features = ["json"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.132"
time = { version = "0.3.55", features = ["serde", "serde-well-known", "parsing", "formatting"] }

[dev-dependencies]
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread", "time"] }
time = { version = "0.3.55", features = ["macros"] }